language: node_js
node_js: "lts/*"
cache: yarn

stages:
  - build

jobs:
  include:
    - stage: build
      before_script: if [[ ! $PWD/ = "/build/JonJam/themeparks-bot" ]]; then cd "/build/JonJam/themeparks-bot"; fi
      script: yarn build