apiVersion: v1
kind: Service
metadata:
  name: {{ include "themeparks-bot.fullname" . }}
  labels:
    app: {{ include "themeparks-bot.name" . }}
    chart: {{ include "themeparks-bot.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    description: "Service for {{ include "themeparks-bot.name" . }}"
spec:
  selector:
    app: {{ include "themeparks-bot.name" . }}
    release: {{ .Release.Name }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      name: http