apiVersion: v1
kind: Secret
metadata:
  name: {{ template "themeparks-bot.fullname" . }}
  labels:
    app: {{ template "themeparks-bot.name" . }}
    chart: {{ template "themeparks-bot.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    description: "Secret for {{ template "themeparks-bot.name" }}"
type: Opaque
data:
  LUIS_APP_URL: {{ required ".Values.secret.luisAppUrl  is required!" .Values.secret.luisAppUrl }}
  STORAGE_ACCOUNT_NAME: {{ required ".Values.secret.storageAccountName is required!" .Values.secret.storageAccountName }}
  STORAGE_ACCOUNT_KEY: {{ required ".Values.secret.storageAccountKey is required!" .Values.secret.storageAccountKey }}
  MICROSOFT_APP_ID: {{ required ".Values.secret.microsoftAppId is required!" .Values.secret.microsoftAppId }}
  MICROSOFT_APP_PASSWORD: {{ required ".Values.secret.microsoftAppPassword is required!" .Values.secret.microsoftAppPassword }}