apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "themeparks-bot.fullname" . }}
  labels:
    app: {{ include "themeparks-bot.name" . }}
    chart: {{ include "themeparks-bot.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    description: "Ingress for {{ include "themeparks-bot.name" . }}"
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - dev-tpb.westeurope.cloudapp.azure.com
    http:
      paths:
      - path: /api/messages
        backend:
          serviceName: {{ include "themeparks-bot.fullname" . }}
          servicePort: http