apiVersion: v1
kind: Service
metadata:
  name: themeparks-bot
spec:
  selector:
    app: themeparks-bot
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  # Change to loadBalancer for non minikube
  type: NodePort
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: themeparks-bot-deployment
  labels:
    app: themeparks-bot
spec:
  # TODO Change to 3
  replicas: 1
  selector:
    matchLabels:
      app: themeparks-bot
  template:
    metadata:
      labels:
        app: themeparks-bot
    spec:
      containers:
      - name: themeparks-bot
        image: themeparks-bot:0.0.2
        ports:
        - containerPort: 8080
        env:
        - name: LUIS_APP_URL
          valueFrom:
            secretKeyRef:
              name: themeparks-bot-secret
              key: LUIS_APP_URL
        - name: STORAGE_ACCOUNT_NAME
          valueFrom:
            secretKeyRef:
              name: themeparks-bot-secret
              key: STORAGE_ACCOUNT_NAME
        - name: STORAGE_ACCOUNT_KEY
          valueFrom:
            secretKeyRef:
              name: themeparks-bot-secret
              key: STORAGE_ACCOUNT_KEY
        - name: MICROSOFT_APP_ID
          valueFrom:
            secretKeyRef:
              name: themeparks-bot-secret
              key: MICROSOFT_APP_ID
        - name: MICROSOFT_APP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: themeparks-bot-secret
              key: MICROSOFT_APP_PASSWORD
