dependencies:
  - name: redis-ha
    version: 2.0.0
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: nginx-ingress
    version: 0.9.4
    repository: https://kubernetes-charts.storage.googleapis.com/